/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItem } from './category-list-response-data-item';
import { CategoryListResponseMeta } from './category-list-response-meta';
/**
 * 
 * @export
 * @interface CategoryListResponse
 */
export interface CategoryListResponse {
    /**
     * 
     * @type {Array<CategoryListResponseDataItem>}
     * @memberof CategoryListResponse
     */
    data?: Array<CategoryListResponseDataItem>;
    /**
     * 
     * @type {CategoryListResponseMeta}
     * @memberof CategoryListResponse
     */
    meta?: CategoryListResponseMeta;
}
