/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolder } from './category-list-response-data-item-attributes-image-data-attributes-folder';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CategoryListResponseDataItemAttributesImageDataAttributesRelated } from './category-list-response-data-item-attributes-image-data-attributes-related';
/**
 * 
 * @export
 * @interface CategoryListResponseDataItemAttributesImageDataAttributes
 */
export interface CategoryListResponseDataItemAttributesImageDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    formats?: any;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    providerMetadata?: any;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    related?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolder}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    folder?: CategoryListResponseDataItemAttributesImageDataAttributesFolder;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    folderPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
