/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRoles } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by-data-attributes-roles';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
/**
 * 
 * @export
 * @interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
 */
export interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    registrationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    isActive?: boolean;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRoles}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    roles?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRoles;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    blocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    preferedLanguage?: string;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
