/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesAttributes } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by-data-attributes-roles-attributes';
/**
 * 
 * @export
 * @interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesData
 */
export interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesData {
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesData
     */
    id?: number;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesAttributes}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesData
     */
    attributes?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedByDataAttributesRolesAttributes;
}
