/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFiles } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CategoryListResponseDataItemAttributesImageDataAttributesRelated } from './category-list-response-data-item-attributes-image-data-attributes-related';
/**
 * 
 * @export
 * @interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
 */
export interface CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    pathId?: number;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    parent?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    children?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFiles}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    files?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFiles;
    /**
     * 
     * @type {string}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
