/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ErrorError
 */
export interface ErrorError {
    /**
     * 
     * @type {number}
     * @memberof ErrorError
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorError
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorError
     */
    message?: string;
    /**
     * 
     * @type {any}
     * @memberof ErrorError
     */
    details?: any;
}
