/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Datetime } from './datetime';
import { UsersPermissionsRole } from './users-permissions-role';
import { UsersPermissionsUser } from './users-permissions-user';
/**
 * 
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 extends UsersPermissionsUser {
    /**
     * 
     * @type {UsersPermissionsRole}
     * @memberof InlineResponse201
     */
    role?: UsersPermissionsRole;
}
