/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { NavigationResponseDataObjectAttributesLocalizations } from './navigation-response-data-object-attributes-localizations';
/**
 * 
 * @export
 * @interface NavigationResponseDataObjectAttributes
 */
export interface NavigationResponseDataObjectAttributes {
    /**
     * 
     * @type {string}
     * @memberof NavigationResponseDataObjectAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof NavigationResponseDataObjectAttributes
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof NavigationResponseDataObjectAttributes
     */
    order?: number;
    /**
     * 
     * @type {Date}
     * @memberof NavigationResponseDataObjectAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof NavigationResponseDataObjectAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy}
     * @memberof NavigationResponseDataObjectAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof NavigationResponseDataObjectAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {NavigationResponseDataObjectAttributesLocalizations}
     * @memberof NavigationResponseDataObjectAttributes
     */
    localizations?: NavigationResponseDataObjectAttributesLocalizations;
    /**
     * 
     * @type {string}
     * @memberof NavigationResponseDataObjectAttributes
     */
    locale?: string;
}
