/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NavigationListResponseDataItemLocalizedAttributes } from './navigation-list-response-data-item-localized-attributes';
/**
 * 
 * @export
 * @interface NavigationListResponseDataItemLocalized
 */
export interface NavigationListResponseDataItemLocalized {
    /**
     * 
     * @type {number}
     * @memberof NavigationListResponseDataItemLocalized
     */
    id?: number;
    /**
     * 
     * @type {NavigationListResponseDataItemLocalizedAttributes}
     * @memberof NavigationListResponseDataItemLocalized
     */
    attributes?: NavigationListResponseDataItemLocalizedAttributes;
}
