/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { ProductListResponseDataItemAttributesProductPropertiesAttributesProduct } from './product-list-response-data-item-attributes-product-properties-attributes-product';
import { ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyType } from './product-list-response-data-item-attributes-product-properties-attributes-property-type';
/**
 * 
 * @export
 * @interface ProductListResponseDataItemAttributesProductPropertiesAttributes
 */
export interface ProductListResponseDataItemAttributesProductPropertiesAttributes {
    /**
     * 
     * @type {ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyType}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    propertyType?: ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyType;
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    value?: string;
    /**
     * 
     * @type {ProductListResponseDataItemAttributesProductPropertiesAttributesProduct}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    product?: ProductListResponseDataItemAttributesProductPropertiesAttributesProduct;
    /**
     * 
     * @type {Date}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
