/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { ProductPropertyListResponseDataItemAttributesProduct } from './product-property-list-response-data-item-attributes-product';
import { ProductPropertyListResponseDataItemAttributesPropertyType } from './product-property-list-response-data-item-attributes-property-type';
/**
 * 
 * @export
 * @interface ProductPropertyListResponseDataItemAttributes
 */
export interface ProductPropertyListResponseDataItemAttributes {
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesPropertyType}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    propertyType?: ProductPropertyListResponseDataItemAttributesPropertyType;
    /**
     * 
     * @type {string}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    value?: string;
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesProduct}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    product?: ProductPropertyListResponseDataItemAttributesProduct;
    /**
     * 
     * @type {Date}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductPropertyListResponseDataItemAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
