/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeDataAttributes } from './product-list-response-data-item-attributes-product-properties-attributes-property-type-data-attributes';
/**
 * 
 * @export
 * @interface ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeData
 */
export interface ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeData {
    /**
     * 
     * @type {number}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeData
     */
    id?: number;
    /**
     * 
     * @type {ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeDataAttributes}
     * @memberof ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeData
     */
    attributes?: ProductListResponseDataItemAttributesProductPropertiesAttributesPropertyTypeDataAttributes;
}
