/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseMeta } from './category-list-response-meta';
import { ProductListResponseDataItem } from './product-list-response-data-item';
/**
 * 
 * @export
 * @interface ProductListResponse
 */
export interface ProductListResponse {
    /**
     * 
     * @type {Array<ProductListResponseDataItem>}
     * @memberof ProductListResponse
     */
    data?: Array<ProductListResponseDataItem>;
    /**
     * 
     * @type {CategoryListResponseMeta}
     * @memberof ProductListResponse
     */
    meta?: CategoryListResponseMeta;
}
