/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductPropertyListResponseDataItemAttributesProductDataAttributesCategoryData } from './product-property-list-response-data-item-attributes-product-data-attributes-category-data';
/**
 * 
 * @export
 * @interface ProductPropertyListResponseDataItemAttributesProductDataAttributesCategory
 */
export interface ProductPropertyListResponseDataItemAttributesProductDataAttributesCategory {
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesProductDataAttributesCategoryData}
     * @memberof ProductPropertyListResponseDataItemAttributesProductDataAttributesCategory
     */
    data?: ProductPropertyListResponseDataItemAttributesProductDataAttributesCategoryData;
}
