/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImage } from './category-list-response-data-item-attributes-image';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CategoryListResponseDataItemAttributesImageDataAttributesRelated } from './category-list-response-data-item-attributes-image-data-attributes-related';
import { ProductListResponseDataItemAttributesCategory } from './product-list-response-data-item-attributes-category';
import { ProductListResponseDataItemAttributesImages } from './product-list-response-data-item-attributes-images';
import { ProductListResponseDataItemAttributesProductProperties } from './product-list-response-data-item-attributes-product-properties';
/**
 * 
 * @export
 * @interface ProductListResponseDataItemAttributes
 */
export interface ProductListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributes
     */
    details?: string;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImage}
     * @memberof ProductListResponseDataItemAttributes
     */
    mainImage?: CategoryListResponseDataItemAttributesImage;
    /**
     * 
     * @type {ProductListResponseDataItemAttributesImages}
     * @memberof ProductListResponseDataItemAttributes
     */
    images?: ProductListResponseDataItemAttributesImages;
    /**
     * 
     * @type {number}
     * @memberof ProductListResponseDataItemAttributes
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductListResponseDataItemAttributes
     */
    discountedPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductListResponseDataItemAttributes
     */
    order?: number;
    /**
     * 
     * @type {ProductListResponseDataItemAttributesCategory}
     * @memberof ProductListResponseDataItemAttributes
     */
    category?: ProductListResponseDataItemAttributesCategory;
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributes
     */
    SKU?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductListResponseDataItemAttributes
     */
    EAN?: string;
    /**
     * 
     * @type {ProductListResponseDataItemAttributesProductProperties}
     * @memberof ProductListResponseDataItemAttributes
     */
    productProperties?: ProductListResponseDataItemAttributesProductProperties;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof ProductListResponseDataItemAttributes
     */
    variants?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {Date}
     * @memberof ProductListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductListResponseDataItemAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductListResponseDataItemAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
