/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductPropertyListResponseDataItemAttributesProductDataAttributes } from './product-property-list-response-data-item-attributes-product-data-attributes';
/**
 * 
 * @export
 * @interface ProductPropertyListResponseDataItemAttributesProductData
 */
export interface ProductPropertyListResponseDataItemAttributesProductData {
    /**
     * 
     * @type {number}
     * @memberof ProductPropertyListResponseDataItemAttributesProductData
     */
    id?: number;
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesProductDataAttributes}
     * @memberof ProductPropertyListResponseDataItemAttributesProductData
     */
    attributes?: ProductPropertyListResponseDataItemAttributesProductDataAttributes;
}
