/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductVariantListResponseDataItemAttributes } from './product-variant-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface ProductVariantResponseDataObject
 */
export interface ProductVariantResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof ProductVariantResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {ProductVariantListResponseDataItemAttributes}
     * @memberof ProductVariantResponseDataObject
     */
    attributes?: ProductVariantListResponseDataItemAttributes;
}
