/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductPropertyListResponseDataItemAttributesPropertyTypeDataAttributes } from './product-property-list-response-data-item-attributes-property-type-data-attributes';
/**
 * 
 * @export
 * @interface ProductPropertyTypeResponseDataObjectLocalized
 */
export interface ProductPropertyTypeResponseDataObjectLocalized {
    /**
     * 
     * @type {number}
     * @memberof ProductPropertyTypeResponseDataObjectLocalized
     */
    id?: number;
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesPropertyTypeDataAttributes}
     * @memberof ProductPropertyTypeResponseDataObjectLocalized
     */
    attributes?: ProductPropertyListResponseDataItemAttributesPropertyTypeDataAttributes;
}
