/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProductRequestData
 */
export interface ProductRequestData {
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    details?: string;
    /**
     * 
     * @type {number | string}
     * @memberof ProductRequestData
     */
    mainImage?: number | string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof ProductRequestData
     */
    images?: Array<number | string>;
    /**
     * 
     * @type {number}
     * @memberof ProductRequestData
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequestData
     */
    discountedPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequestData
     */
    order?: number;
    /**
     * 
     * @type {number | string}
     * @memberof ProductRequestData
     */
    category?: number | string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    SKU?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    EAN?: string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof ProductRequestData
     */
    productProperties?: Array<number | string>;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof ProductRequestData
     */
    variants?: Array<number | string>;
}
