/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductPropertyListResponseDataItemAttributesProductDataAttributesProductPropertiesData } from './product-property-list-response-data-item-attributes-product-data-attributes-product-properties-data';
/**
 * 
 * @export
 * @interface ProductPropertyListResponseDataItemAttributesProductDataAttributesProductProperties
 */
export interface ProductPropertyListResponseDataItemAttributesProductDataAttributesProductProperties {
    /**
     * 
     * @type {Array<ProductPropertyListResponseDataItemAttributesProductDataAttributesProductPropertiesData>}
     * @memberof ProductPropertyListResponseDataItemAttributesProductDataAttributesProductProperties
     */
    data?: Array<ProductPropertyListResponseDataItemAttributesProductDataAttributesProductPropertiesData>;
}
