/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductPropertyListResponseDataItemAttributesPropertyTypeData } from './product-property-list-response-data-item-attributes-property-type-data';
/**
 * 
 * @export
 * @interface ProductPropertyListResponseDataItemAttributesPropertyType
 */
export interface ProductPropertyListResponseDataItemAttributesPropertyType {
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesPropertyTypeData}
     * @memberof ProductPropertyListResponseDataItemAttributesPropertyType
     */
    data?: ProductPropertyListResponseDataItemAttributesPropertyTypeData;
}
