/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductListResponseDataItemAttributes } from './product-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface ProductResponseDataObject
 */
export interface ProductResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {ProductListResponseDataItemAttributes}
     * @memberof ProductResponseDataObject
     */
    attributes?: ProductListResponseDataItemAttributes;
}
