/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { ProductPropertyListResponseDataItemAttributesPropertyType } from './product-property-list-response-data-item-attributes-property-type';
import { ProductVariantListResponseDataItemAttributesProducts } from './product-variant-list-response-data-item-attributes-products';
/**
 * 
 * @export
 * @interface ProductVariantListResponseDataItemAttributes
 */
export interface ProductVariantListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    name?: string;
    /**
     * 
     * @type {ProductPropertyListResponseDataItemAttributesPropertyType}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    propertyType?: ProductPropertyListResponseDataItemAttributesPropertyType;
    /**
     * 
     * @type {ProductVariantListResponseDataItemAttributesProducts}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    products?: ProductVariantListResponseDataItemAttributesProducts;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof ProductVariantListResponseDataItemAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
