/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
/**
 * 
 * @export
 * @interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
 */
export interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes {
    /**
     * 
     * @type {string}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    action?: string;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    role?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
