/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleData } from './rating-list-response-data-item-attributes-users-permissions-user-data-attributes-role-data';
/**
 * 
 * @export
 * @interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole
 */
export interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole {
    /**
     * 
     * @type {RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleData}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole
     */
    data?: RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleData;
}
