/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CategoryListResponseDataItemAttributesImageDataAttributesRelated } from './category-list-response-data-item-attributes-image-data-attributes-related';
import { RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions } from './rating-list-response-data-item-attributes-users-permissions-user-data-attributes-role-data-attributes-permissions';
/**
 * 
 * @export
 * @interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
 */
export interface RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    type?: string;
    /**
     * 
     * @type {RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    permissions?: RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    users?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
