/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributes } from './rating-list-response-data-item-attributes-users-permissions-user-data-attributes';
/**
 * 
 * @export
 * @interface RatingListResponseDataItemAttributesUsersPermissionsUserData
 */
export interface RatingListResponseDataItemAttributesUsersPermissionsUserData {
    /**
     * 
     * @type {number}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserData
     */
    id?: number;
    /**
     * 
     * @type {RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributes}
     * @memberof RatingListResponseDataItemAttributesUsersPermissionsUserData
     */
    attributes?: RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributes;
}
