/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { RatingListResponseDataItemAttributesProduct } from './rating-list-response-data-item-attributes-product';
import { RatingListResponseDataItemAttributesUsersPermissionsUser } from './rating-list-response-data-item-attributes-users-permissions-user';
/**
 * 
 * @export
 * @interface RatingListResponseDataItemAttributes
 */
export interface RatingListResponseDataItemAttributes {
    /**
     * 
     * @type {number}
     * @memberof RatingListResponseDataItemAttributes
     */
    rating?: number;
    /**
     * 
     * @type {RatingListResponseDataItemAttributesUsersPermissionsUser}
     * @memberof RatingListResponseDataItemAttributes
     */
    usersPermissionsUser?: RatingListResponseDataItemAttributesUsersPermissionsUser;
    /**
     * 
     * @type {RatingListResponseDataItemAttributesProduct}
     * @memberof RatingListResponseDataItemAttributes
     */
    product?: RatingListResponseDataItemAttributesProduct;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RatingListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RatingListResponseDataItemAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
