/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolder } from './category-list-response-data-item-attributes-image-data-attributes-folder';
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CategoryListResponseDataItemAttributesImageDataAttributesRelated } from './category-list-response-data-item-attributes-image-data-attributes-related';
/**
 * 
 * @export
 * @interface UploadFolderListResponseDataItemAttributes
 */
export interface UploadFolderListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    pathId?: number;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolder}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    parent?: CategoryListResponseDataItemAttributesImageDataAttributesFolder;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    children?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    files?: CategoryListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {string}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UploadFolderListResponseDataItemAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
