/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UploadFolderRequestData
 */
export interface UploadFolderRequestData {
    /**
     * 
     * @type {string}
     * @memberof UploadFolderRequestData
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFolderRequestData
     */
    pathId: number;
    /**
     * 
     * @type {number | string}
     * @memberof UploadFolderRequestData
     */
    parent?: number | string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UploadFolderRequestData
     */
    children?: Array<number | string>;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UploadFolderRequestData
     */
    files?: Array<number | string>;
    /**
     * 
     * @type {string}
     * @memberof UploadFolderRequestData
     */
    path: string;
}
