/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UploadFileRequestData
 */
export interface UploadFileRequestData {
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFileRequestData
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof UploadFileRequestData
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof UploadFileRequestData
     */
    formats?: any;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    mime: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFileRequestData
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    provider: string;
    /**
     * 
     * @type {any}
     * @memberof UploadFileRequestData
     */
    providerMetadata?: any;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UploadFileRequestData
     */
    related?: Array<number | string>;
    /**
     * 
     * @type {number | string}
     * @memberof UploadFileRequestData
     */
    folder?: number | string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequestData
     */
    folderPath: string;
}
