/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UploadFolderListResponseDataItemAttributes } from './upload-folder-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface UploadFolderListResponseDataItemLocalized
 */
export interface UploadFolderListResponseDataItemLocalized {
    /**
     * 
     * @type {number}
     * @memberof UploadFolderListResponseDataItemLocalized
     */
    id?: number;
    /**
     * 
     * @type {UploadFolderListResponseDataItemAttributes}
     * @memberof UploadFolderListResponseDataItemLocalized
     */
    attributes?: UploadFolderListResponseDataItemAttributes;
}
