/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UploadFolderResponseDataObject } from './upload-folder-response-data-object';
/**
 * 
 * @export
 * @interface UploadFolderResponse
 */
export interface UploadFolderResponse {
    /**
     * 
     * @type {UploadFolderResponseDataObject}
     * @memberof UploadFolderResponse
     */
    data?: UploadFolderResponseDataObject;
    /**
     * 
     * @type {any}
     * @memberof UploadFolderResponse
     */
    meta?: any;
}
