/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
/**
 * 
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    confirmationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    blocked?: boolean;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    role?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
