/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsUserListResponseDataItemAttributes } from './users-permissions-user-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface UsersPermissionsUserListResponseDataItemLocalized
 */
export interface UsersPermissionsUserListResponseDataItemLocalized {
    /**
     * 
     * @type {number}
     * @memberof UsersPermissionsUserListResponseDataItemLocalized
     */
    id?: number;
    /**
     * 
     * @type {UsersPermissionsUserListResponseDataItemAttributes}
     * @memberof UsersPermissionsUserListResponseDataItemLocalized
     */
    attributes?: UsersPermissionsUserListResponseDataItemAttributes;
}
