/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes } from './users-permissions-permission-list-response-data-item-attributes-role-data-attributes-users-attributes';
/**
 * 
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersData
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersData {
    /**
     * 
     * @type {number}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersData
     */
    id?: number;
    /**
     * 
     * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersData
     */
    attributes?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersAttributes;
}
