/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributes } from './users-permissions-role-list-response-data-item-attributes-permissions-attributes';
/**
 * 
 * @export
 * @interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsData
 */
export interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsData {
    /**
     * 
     * @type {number}
     * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsData
     */
    id?: number;
    /**
     * 
     * @type {UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributes}
     * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsData
     */
    attributes?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributes;
}
