/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsRoleRequestData
 */
export interface UsersPermissionsRoleRequestData {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleRequestData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleRequestData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleRequestData
     */
    type?: string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UsersPermissionsRoleRequestData
     */
    permissions?: Array<number | string>;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UsersPermissionsRoleRequestData
     */
    users?: Array<number | string>;
}
