/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Datetime } from './datetime';
/**
 * 
 * @export
 * @interface UsersPermissionsUser
 */
export interface UsersPermissionsUser {
    /**
     * 
     * @type {number}
     * @memberof UsersPermissionsUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    blocked?: boolean;
    /**
     * 
     * @type {Datetime}
     * @memberof UsersPermissionsUser
     */
    createdAt?: Datetime;
    /**
     * 
     * @type {Datetime}
     * @memberof UsersPermissionsUser
     */
    updatedAt?: Datetime;
}
