/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './category-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions } from './rating-list-response-data-item-attributes-users-permissions-user-data-attributes-role-data-attributes-permissions';
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers } from './users-permissions-permission-list-response-data-item-attributes-role-data-attributes-users';
/**
 * 
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    type?: string;
    /**
     * 
     * @type {RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    permissions?: RatingListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions;
    /**
     * 
     * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    users?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    createdBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes
     */
    updatedBy?: CategoryListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
