/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsUserRequestData
 */
export interface UsersPermissionsUserRequestData {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    confirmationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUserRequestData
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUserRequestData
     */
    blocked?: boolean;
    /**
     * 
     * @type {number | string}
     * @memberof UsersPermissionsUserRequestData
     */
    role?: number | string;
}
