/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsPermissionResponseDataObject } from './users-permissions-permission-response-data-object';
/**
 * 
 * @export
 * @interface UsersPermissionsPermissionResponse
 */
export interface UsersPermissionsPermissionResponse {
    /**
     * 
     * @type {UsersPermissionsPermissionResponseDataObject}
     * @memberof UsersPermissionsPermissionResponse
     */
    data?: UsersPermissionsPermissionResponseDataObject;
    /**
     * 
     * @type {any}
     * @memberof UsersPermissionsPermissionResponse
     */
    meta?: any;
}
